version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Docker/DOCKERFILE.http-be
    ports:
      - "8000:8000"
  ws:
    build:
      context: .
      dockerfile: Docker/DOCKERFILE.ws
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: Docker/DOCKERFILE.web
    ports:
      - "3000:3000"
