version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Docker/DOCKERFILE.http-be
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  ws:
    build:
      context: .
      dockerfile: Docker/DOCKERFILE.ws
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: Docker/DOCKERFILE.web
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: timescaledb
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5433:5432"
